version: "2"
run:
  concurrency: 6
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - dogsled
    - durationcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - lll
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    - protogetter
    - reassign
    - recvcheck
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - usestdlibvars
    - usetesting
    - whitespace
    - wrapcheck
    - zerologlint
  disable:
    - exhaustruct
    - testpackage
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    exhaustive:
      default-signifies-exhaustive: true
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print.*$
          msg: Do not commit print statements. Output to stdout interferes with users who redirect JSON results to files.
    gocritic:
      disable-all: true
      enabled-checks:
        - appendAssign
        - argOrder
        - badCall
        - badCond
        - caseOrder
        - codegenComment
        - commentedOutCode
        - deprecatedComment
        - dupArg
        - dupBranchBody
        - dupCase
        - dupSubExpr
        - exitAfterDefer
        - flagDeref
        - flagName
        - mapKey
        - nilValReturn
        - octalLiteral
        - offBy1
        - sloppyLen
        - sloppyTypeAssert
        - weakCond
        - appendCombine
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
        - assignOp
        - boolExprSimplify
        - captLocal
        - commentedOutImport
        - commentFormatting
        - defaultCaseOrder
        - docStub
        - elseif
        - emptyFallthrough
        - hexLiteral
        - ifElseChain
        - methodExprCall
        - newDeref
        - regexpMust
        - singleCaseSwitch
        - switchTrue
        - typeAssertChain
        - typeSwitchVar
        - underef
        - unlabelStmt
        - unlambda
        - unslice
        - valSwap
        - wrapperFunc
        - builtinShadow
        - importShadow
        - initClause
        - nestingReduce
        - paramTypeCombine
        - ptrToRefParam
        - typeUnparen
        - unnecessaryBlock
    godox:
      keywords:
        - BUG
        - FIXME
        - HACK
    gosec:
      excludes:
        - G115
    govet:
      enable:
        - fieldalignment
    nolintlint:
      require-specific: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - err113
          - funlen
          - goconst
          - gocyclo
          - lll
          - wrapcheck
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: ""
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/ossf/allstar)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
