steps:
- name: golang:1.17
  entrypoint: go
  args: ['install', 'github.com/google/ko@v0.10.0']
- name: golang:1.17
  entrypoint: bash
  args: ['-c', 'KO_DOCKER_REPO="gcr.io/allstar-ossf" /go/bin/ko publish ./cmd/allstar > container']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args: ['-c', 'gcloud app deploy --appyaml=app-staging.yaml --project=allstar-ossf --image-url $(cat container)']
timeout: 1200s
options:
  volumes:
  - name: go-modules
    path: /go
