name: "GW Validate Workflow"
on: [push, pull_request]

jobs:
  gw_validat3:
    name: "GW Validate Job"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: gradle/wrapper-validation-action@Commit-B-4
