name: "GW Validate Workflow"
on: [push, pull_request]

jobs:
  gw_validate:
    name: "GW Validate Job"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1.0.4
